// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateEmployee struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	JobTitle    string `json:"job_title"`
	Email       string `json:"email"`
	SlackID     string `json:"slack_id"`
	SlackHandle string `json:"slack_handle"`
}

type Employee struct {
	ID          string `json:"id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	JobTitle    string `json:"job_title"`
	Email       string `json:"email"`
	SlackID     string `json:"slack_id"`
	SlackHandle string `json:"slack_handle"`
}
