const categories = [
  'Alcohol store',
  'Apparel',
  'Art Dealers and Galleries',
  'Drugstores, Chemists, Pharmacies',
  'Food / Grocery',
  'Newsstand / Magazines',
  'Other Retail',
  'Outdoor Market',
  'Tobacco and eCigarettes',
  'Cleaning Services',
  'Consulting',
  'Craftsman / Contractor',
  'Education',
  'Letting agents',
  'Motor Freight Carriers and Trucking',
  'Professional Services',
  'Taxi / Limo',
  'Beauty / Barber',
  'Dentistry',
  'Fitness / Wellness / Spa',
  'Medical Practitioner',
  'Medical Services',
  'Veterinary',
  'Music / Concerts / Cinema',
  'Recreation / Entertainment',
  'Tourism',
  'Bar / Club',
  'Café / Restaurant',
  'Catering / Delivery',
  'Fast Food Restaurant',
  'Food Truck / Cart',
  'Hotel / Accommodation',
  'Charitable Organisation',
  'Membership Organisation',
  'Political Organisation',
];

export const businessOptions = categories.map((category) => ({
  value: category,
  label: category,
}));
