export const businessOptions = [
  { value: "5921", label: "Alcohol store" },
  { value: "5691", label: "Apparel" },
  { value: "5971", label: "Art Dealers and Galleries" },
  { value: "5912", label: "Drugstores, Chemists, Pharmacies" },
  { value: "5411", label: "Food / Grocery" },
  { value: "5994", label: "Newsstand / Magazines" },
  { value: "5999", label: "Other Retail" },
  { value: "5399", label: "Outdoor Market" },
  { value: "5993", label: "Tobacco and eCigarettes" },
  { value: "7210", label: "Cleaning Services" },
  { value: "7392", label: "Consulting" },
  { value: "1520", label: "Craftsman / Contractor" },
  { value: "8299", label: "Education" },
  { value: "6513", label: "Letting agents" },
  { value: "4214", label: "Motor Freight Carriers and Trucking" },
  { value: "8999", label: "Professional Services" },
  { value: "4121", label: "Taxi / Limo" },
  { value: "7230", label: "Beauty / Barber" },
  { value: "8021", label: "Dentistry" },
  { value: "7298", label: "Fitness / Wellness / Spa" },
  { value: "8011", label: "Medical Practitioner" },
  { value: "8099", label: "Medical Services" },
  { value: "0742", label: "Veterinary" },
  { value: "7922", label: "Music / Concerts / Cinema" },
  { value: "7999", label: "Recreation / Entertainment" },
  { value: "7991", label: "Tourism" },
  { value: "5813", label: "Bar / Club" },
  { value: "5812", label: "Café / Restaurant" },
  { value: "5811", label: "Catering / Delivery" },
  { value: "5814", label: "Fast Food Restaurant" },
  { value: "5499", label: "Food Truck / Cart" },
  { value: "7011", label: "Hotel / Accommodation" },
  { value: "8398", label: "Charitable Organisation" },
  { value: "8699", label: "Membership Organisation" },
  { value: "8651", label: "Political Organisation" },
];
